crypto_dbt:
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: /Users/gustawkempa/.cursor-tutor/crypto_tracker_project/data/raw/raw_data.db
      schema: main
      schemas_and_paths:
       main: '/Users/gustawkempa/.cursor-tutor/crypto_tracker_project/data/raw/raw_data.db'
      schema_directory: '/Users/gustawkempa/.cursor-tutor/crypto_tracker_project/data/raw'
  target: dev