crypto_dbt:
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: "{{ env_var('DBT_SQLITE_PATH') }}"
      schema: main
      schemas_and_paths:
        main: "{{ env_var('DBT_SQLITE_PATH') }}"
      schema_directory: "{{ env_var('DBT_SQLITE_DIR') }}"
  target: dev
